### ISSUE TITLE
Python library to do the same thing

### ISSUE THREAD

**Issue by djc** [mkrcah/abnamro-tx#1]
FYI, you might be interested in the Python library I just published:

https://github.com/djc/abna

I reverse engineered the login process, so you can now make requests to the internet banking services without having to run a headless browser engine.

**Comment by mkrcah** [comment]
Thanks a lot for let me know. I'll add this to the README.

**Comment by djc** [comment]
Thanks! I've added a link to this project to my README, as well.

**Comment by mkrcah** [comment]
Cool, thanks
